name:                poseidon-http-server
version:             0.0.1
github:              "githubuser/poseidon-http-server"
license:             BSD3
author:              "Stephan Schiffels"
maintainer:          "stephan_schiffels@eva.mpg.de"
copyright:           "2021 Stephan Schiffels"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/githubuser/poseidon-http-server#readme>

dependencies:
- base >= 4.7 && < 5

executables:
  poseidon-http-server:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
